version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "<stack-name>"
s3_bucket = "<bucket-name>"
s3_prefix = "<bucket-prefix>"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentParam=\"<env>\"" # Enter npe or prod